update healthcheck to become a parameter
litmuschaos/litmus-python pull request #14
Opened 2021-02-03 01:13 UTC by sharpyy

- update healthcheck to become a parameter and not a hardcoded value
- reformated the JSON files

2021-02-16 18:32 UTC, sumitnagal commented
@sharpyy , can you handle the line spacing as well as space .. to make only changes to come in PR.

2021-02-16 21:52 UTC, sumitnagal commented
@sharpyy , the only change coming in PR should be new or modified lines

2021-02-17 06:07 UTC, sumitnagal commented
you need to use this variable and define it as default in wrapper https://github.com/litmuschaos/litmus-python/blob/master/chaos-test/chaostest/chaostest/kubernetes/k8_wrapper.py

2021-02-17 06:07 UTC, sumitnagal commented
@sharpyy , please see why the CI is failing

2021-02-17 06:07 UTC, sumitnagal commented on chaos-test/chaostest/chaostest/json/service-app-kill-health.json
> +          "url": "https://${service_url}/health/full",
You need to change and use the service_healthcheck endpoint

2021-02-17 18:05 UTC, vijayto commented on chaos-test/chaostest/chaostest/json/pod-app-kill-all.json
> +    "service_healthcheck": {
@sharpyy this looks good to me, however I think it might be a good idea to have a default value specified for service_healthcheck

2021-02-17 18:08 UTC, vijayto commented on chaos-test/chaostest/chaostest/json/pod-app-kill-all.json
> +    "service_healthcheck": {
Something like this 
```
"type" : "env",
 "key" : "HEALTH_CHECK_ENDPOINT",
"default" : "/health/full"

````

Most importantly we should be using the environment variable name as key , not the value

2021-02-17 18:08 UTC, vijayto requested changes
@sharpyy have a few comments please check

2021-02-18 01:43 UTC, sumitnagal commented on chaos-test/chaostest/chaostest/kubernetes/k8_wrapper.py
> +parser.add_argument('-app-healthcheck', action='store',
LGTM,

2021-02-18 01:45 UTC, sumitnagal approved these changes
@sharpyy  This looks good to me, please make a small change suggested before merging.

2021-02-18 01:48 UTC, sumitnagal commented on chaos-test/chaostest/chaostest/json/service-app-kill-health.json
> +          "url": "https://${service_url}/health/full",
@sharpyy , please look above you might have missed add APP_ENDPOINT

2021-02-18 23:01 UTC, sharpyy commented
I updated the PR title for clarification. Please merge.

> @sharpyy have a few comments please check

I did update the commented lines. Thanks for reviewing

2021-02-18 23:06 UTC, merged